version: '3.9'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/uploads:/app/uploads
      - ./api/logs:/app/logs
    ports:
      - 8001:8000
    networks:
      - default
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - default
    restart: unless-stopped

networks:
  default:
