version: '3.9'

services:
  traefik:
    image: traefik:2.9
    ports:
      - 80:80 # http port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config/rules.yml:/etc/traefik/rules.yml:ro
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
