# network entrypoint into traefik
entryPoints:
  web:
    address: ":80"
    # proxyProtocol:
    #   insecure: true
    # forwardedHeaders:
    #   insecure: true

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/rules.yml
    watch: true

# API and dashboard configuration
api:
  dashboard: true

# log:
#   level: DEBUG
